### ISSUE TITLE
ALsizei improperly mapped to IntPtr

### ISSUE THREAD

**Issue by manu-silicon** [flibitijibibo/OpenAL-CS#1]
It seems that the OpenAL data type `ALsizei` is mapped to IntPtr in the C# wrapper, but the C definition is clear that it is a 32-bit integer. It should therefore be mapped to `int`.

**Comment by flibitijibibo** [comment]
Will deal with this tomorrow.

**Comment by flibitijibibo** [comment]
Fixed:

https://github.com/flibitijibibo/OpenAL-CS/commit/0dc69f738f87ca1f35aa4efcfa9e952e83959b21
https://github.com/flibitijibibo/OpenAL-CS/commit/ada14a8bc5659abf48156d4d75b24fc07235ca98

Just for the record, I want everyone to know that for some reason this worked on Win32, Linux 32/64, and OSX 32/64. I don't know either.

**Comment by manu-silicon** [comment]
That was fast. Thanks!
