### ISSUE TITLE
Compile against PCL

### ISSUE THREAD

**Issue by manu-st** [flibitijibibo/OpenAL-CS#2]
Would it be possible to change the .csproj to target AnyCPU, and the PCL? This would make it possible to compile against CoreCLR too. I can submit the PR for that.

**Comment by flibitijibibo** [comment]
AnyCPU I can add, are PCL and CoreCLR going to ruin everything like they did with SDL2#?

**Comment by manu-silicon** [comment]
Here it is just a change in the .csproj. No changes in the code.

**Comment by flibitijibibo** [comment]
I've added AnyCPU/x64 targets to OpenAL#:

https://github.com/flibitijibibo/OpenAL-CS/commit/587a0376b806b84d14756520611f17898b832f95

**Comment by manu-silicon** [comment]
Great. So then the only thing necessary to make this portable are the following changes:

Adding early in the .csproj, just before the first PropertyGroup:
`<Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />`

Then use:
`<ProjectTypeGuids>{786C830F-07A1-408B-BD7F-6EE04809D6DB};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids>
 <TargetFrameworkProfile>Profile78</TargetFrameworkProfile>
 <TargetFrameworkVersion>v4.5</TargetFrameworkVersion>`

And replace the line that refers to the CSharp.targets by

`<Import Project="$(MSBuildExtensionsPath32)\Microsoft\Portable\$(TargetFrameworkVersion)\Microsoft.Portable.CSharp.targets" />`

**Comment by flibitijibibo** [comment]
Cool, I'll leave this as Lazy Documentation(TM) for when FNA starts rolling out with CoreCLR, similar to SDL2#. Thanks for the info!

**Comment by flibitijibibo** [comment]
Added a .NET Standard 2.0 project, similar to FNA and SDL2#:

https://github.com/flibitijibibo/OpenAL-CS/commit/381275db51451260d08cdd3fa0152f46aa1727c4
