### ISSUE TITLE
Update to OpenAL 1.19.1

### ISSUE THREAD

**Issue by Krakean** [flibitijibibo/OpenAL-CS#4]
Hello
Can you please update OpenAL-CS to OpenAL 1.19.1?

**Comment by flibitijibibo** [comment]
Done!

You’ll notice that nothing’s changed however, since I only wrote in extensions that I needed. If you need an extension, write it in and send me the changes.

**Comment by flibitijibibo** [comment]
Closing due to old age, and technically we're updated...
